### ISSUE TITLE
[offtopic] "Proposed challenges for Python AST hackers"

### ISSUE THREAD

**Issue by pfalcon** [isidentical/astvalidate#1]
Hi @isidentical! I'm really writing under impression of https://github.com/isidentical-archive/pepgrave . Perhaps this even should have been posted there, but it residing in `isidentical-archive` doesn't give high hopes, so I'm sorry for posting in a more fresh AST-hacking project. (I also mind that you don't github-watch this project either, so wouldn't receive notifications of any ticket submissions, hence @-mention, hopefully that will reach you.)

So, well, seeing you're an ardent Python AST hacker, I wonder if you thought about hacking up something like this: https://github.com/pfalcon/python-ast-hacking-challenges/issues . https://github.com/pfalcon/python-ast-hacking-challenges/issues/1 is really a warm-up, it's not really a challenge, mostly a gruntwork, I actually would be more interested in a feedback on the fact that Python becomes ~ the only mainstream scripting language which doesn't have const'ness in the core (yeah, lately I learned that even Lua added const modfier in 5.4), and whether the solution should be as radical as adding a prefix keyword (vs e.g. moving typing.Final somewhere like `__future__`).

The real meaty task is https://github.com/pfalcon/python-ast-hacking-challenges/issues/2. I wonder if you're interested in stuff like that.

Any feedback is appreciated.

Thanks!

**Comment by isidentical** [comment]
Hey there! Do you use any real time messaging software? Like discord, telegram or IRC.

**Comment by pfalcon** [comment]
I kinda use, though real time synchronization is the usual problem ;-). I'm the same nick (pfalcon) on freenode IRC (about the same timezone as you).
